- name: Install Vector (Debian)
  apt:
    deb: "https://packages.timber.io/vector/{{ version }}/vector-{{ arch }}.deb"
    install_recommends: yes
  notify:
    - restart vector
  vars:
    version: "{{ vector_nightly | ternary('nightly/latest','latest') }}"
    arch: "{{ vector_debian_arch[ansible_machine] }}"
  when: ansible_os_family == 'Debian'

- name: Install Vector (RedHat)
  yum:
    name: "https://packages.timber.io/vector/{{ version }}/vector-{{ arch }}.rpm"
    state: present
    disable_gpg_check: yes # package is not signed
  notify:
    - restart vector
  vars:
    version: "{{ vector_nightly | ternary('nightly/latest','latest') }}"
    arch: "{{ vector_redhat_arch[ansible_machine] }}"
  when: ansible_os_family == 'RedHat'

- name: Copy config
  template:
    src: templates/vector.toml.j2
    dest: /etc/vector/vector.toml
    mode: 0644
  notify: restart vector

- name: Add vector user to docker group
  user:
    name: vector
    groups: docker
    append: yes
  when: add_vector_docker_group | default(no)
  notify: restart vector

- name: Add vector user to systemd-journal group
  user:
    name: vector
    groups: systemd-journal
    append: yes
  when: add_vector_journal_group | default(no)
  notify: restart vector

- name: Start Vector
  service:
    state: started
    enabled: yes
    name: vector
