vector_template: vector.toml.j2
vector_config_file: /etc/vector/vector.toml
vector_nightly: false
vector_version: "{{ vector_nightly | ternary('nightly','latest') }}"
add_vector_docker_group: false
add_vector_journal_group: false
vector_install_from_repo: false

